### ISSUE TITLE
Move examples to aws-lambda-powertools-java repository

### ISSUE THREAD

**Issue by scottgerring** [aws-samples/aws-lambda-powertools-examples#295]
As part of awslabs/aws-lambda-powertools-java/issues/1050 and awslabs/aws-lambda-powertools-java/pull/1051 these examples will be moved into the main aws-lambda-powertools-java repo. The contents of this repository should be replaced with a message forwarding the user onwards to their new home.

**Comment by msailes** [comment]
Moved
